

CREATE TABLE PEOPLE (
	PEOPLE_ID INT PRIMARY KEY NOT NULL,
	NAME CHAR(50) NOT NULL,
	WORKPLACE CHAR(50) NOT NULL,
);

CREATE TABLE COOPERATION (
	PEOPLE_ID1 INT NOT NULL REFERENCES PEOPLE (PEOPLE_ID),
	PEOPLE_ID2 INT NOT NULL REFERENCES PEOPLE (PEOPLE_ID),
	START DATE,
	DURATION INTERVAL,
	PROJECT_NAME CHAR(200) NOT NULL,
	CHECK (PEOPLE_ID1 < PEOPLE_ID2),
	PRIMARY KEY (PEOPLE_ID1, PEOPLE_ID2, START)
);
