# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-08-11 13:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompaniedUsers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_company', models.TextField(max_length=140)),
                ('user_table_id', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Companys',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.TextField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Cooperation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.IntegerField(default=30)),
                ('project', models.TextField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='ToVerify',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.TextField(max_length=30)),
                ('password', models.CharField(max_length=100)),
                ('status', models.IntegerField(default=1)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Companys')),
            ],
        ),
        migrations.AddField(
            model_name='toverify',
            name='verifiee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='toverify_verifiee', to='user.Users'),
        ),
        migrations.AddField(
            model_name='toverify',
            name='verifier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='toverify_verifier', to='user.Users'),
        ),
        migrations.AddField(
            model_name='cooperation',
            name='contractee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cooperation_contractee', to='user.Users'),
        ),
        migrations.AddField(
            model_name='cooperation',
            name='contractee_company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cooperation_contractee_company', to='user.Companys'),
        ),
        migrations.AddField(
            model_name='cooperation',
            name='contractor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cooperation_contractor', to='user.Users'),
        ),
        migrations.AddField(
            model_name='cooperation',
            name='contractor_company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cooperation_contractor_company', to='user.Companys'),
        ),
    ]
