# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-08-27 07:15
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Companys',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.TextField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Experiences',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('todo', models.IntegerField(default=5)),
                ('start', models.DateField(default=datetime.date.today)),
                ('duration', models.IntegerField(default=1)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Companys')),
            ],
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.TextField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ToVerify',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('experience', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Experiences')),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.TextField(max_length=30)),
                ('password', models.CharField(max_length=100)),
                ('cell', models.TextField(max_length=20)),
                ('position', models.TextField(max_length=10)),
                ('card_id', models.TextField(max_length=19)),
                ('thumbnail_id', models.TextField(max_length=32)),
            ],
        ),
        migrations.AddField(
            model_name='toverify',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Users'),
        ),
        migrations.AddField(
            model_name='experiences',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Projects'),
        ),
        migrations.AddField(
            model_name='experiences',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Users'),
        ),
    ]
